version: "3"

networks:
  payments:

services:
  nginx:
    container_name: "booking_nginx"
    image: nginx:stable-alpine
    networks:
      - payments
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: "booking_php"
    networks:
      - payments
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"

  frontend:
    container_name: "booking_frontend"
    networks:
      - payments
    build:
      context: .
      dockerfile: dockerfiles/vue.dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3001:3001"
    depends_on:
      - nginx
      - php


